version: "3.9"
services:
    mysql:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3309:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8082:8080
